DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS STYLES;
DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE AUTHORS
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);

CREATE TABLE STYLES
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255)
);

CREATE TABLE BOOKS
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT,
    STYLE_ID  BIGINT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID) ON DELETE SET NULL,
    FOREIGN KEY (STYLE_ID) REFERENCES STYLES (ID) ON DELETE SET NULL
--     FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID) ON DELETE NO ACTION,
--     FOREIGN KEY (STYLE_ID) REFERENCES STYLES (ID) ON DELETE NO ACTION
);

CREATE TABLE COMMENTS
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    BOOK_ID  BIGINT,
    TEXT VARCHAR(255),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE SET NULL
);

-- CREATE TABLE BOOKS_COMMENTS
-- (
--     BOOK_ID BIGINT NOT NULL unique,
--     COMMENTS_ID BIGINT NOT NULL unique,
--     FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID) ON DELETE SET NULL,
--     FOREIGN KEY (COMMENTS_ID) REFERENCES COMMENTS (ID) ON DELETE SET NULL
-- )

-- DROP TABLE IF EXISTS TMP_ONE;
-- DROP TABLE IF EXISTS TMP_TWO;
-- DROP TABLE IF EXISTS TMP_TREE;


-- CREATE TABLE TMP_TWO
-- (
--     ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
--     NAME VARCHAR(255)
-- );
--
-- CREATE TABLE TMP_TREE
-- (
--     ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
--     NAME VARCHAR(255)
-- );
--
--
-- CREATE TABLE TMP_ONE
-- (
--     ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
--     TMP_TWO_ID BIGINT,
--     TMP_TREE_ID BIGINT,
--     NAME VARCHAR(255),
--     FOREIGN KEY (TMP_TWO_ID) REFERENCES TMP_TWO (ID) ON DELETE SET NULL,
--     FOREIGN KEY (TMP_TREE_ID) REFERENCES TMP_TREE (ID) ON DELETE SET NULL
-- );
